import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  // next-env.d.ts is generated by Next.js and uses triple-slash references.
  // reference/** is the gitignored private reference project (also excluded in
  // tsconfig.json) — linting it only produces noise about someone else's code.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "design/**",
      "reference/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
